# resolver: lts-16.10
resolver: nightly-2024-01-26

packages:
  - '.'

extra-deps:
- intern-0.9.2
- located-base-0.1.1.1
- text-format-0.3.2
- tasty-rerun-1.1.14
- rest-rewrite-0.4.2

# compiler: ghc-8.10.2
allow-newer: true
